//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code wird erneut generiert. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Account {
    
    
    public partial class Register {
        
        /// <summary>
        /// ErrorMessage-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ErrorMessage;
        
        /// <summary>
        /// E-Mail-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Email;
        
        /// <summary>
        /// password-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Password;
        
        /// <summary>
        /// confirmPassword-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ConfirmPassword;
    }
}
